# Use root/example as user/password credentials
# Use https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee to continue to build out
services:
  db:
    image: mysql:8.0.38
    container_name: labDB
    restart: always
    env_file: 
      - ".env.local"
    environment:
      MYSQL_DATABASE: 'labDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql
# Names our volume
volumes:
  db-volume: